# Generated by Django 4.1.3 on 2022-11-11 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColorPixel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=64)),
                ('color', models.CharField(max_length=64)),
                ('paintArea', models.IntegerField()),
                ('xCoordinate', models.IntegerField()),
                ('yCoordinate', models.IntegerField()),
            ],
        ),
    ]
