# Generated by Django 4.1.3 on 2022-11-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintByNumberMeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorpixel',
            name='colorNumber',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
