# Generated by Django 4.1.3 on 2022-11-15 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintByNumberMeApp', '0002_colorpixel_colornumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colorpixel',
            name='xCoordinate',
        ),
        migrations.RemoveField(
            model_name='colorpixel',
            name='yCoordinate',
        ),
        migrations.AddField(
            model_name='colorpixel',
            name='coordinates',
            field=models.TextField(default=''),
        ),
    ]
