# Generated by Django 4.1.3 on 2022-11-15 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintByNumberMeApp', '0003_remove_colorpixel_xcoordinate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorpixel',
            name='coordinates',
            field=models.JSONField(),
        ),
    ]
