# Generated by Django 4.1.3 on 2022-11-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintByNumberMeApp', '0004_alter_colorpixel_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorpixel',
            name='areaSize',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='colorpixel',
            name='xCenter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='colorpixel',
            name='yCenter',
            field=models.IntegerField(default=0),
        ),
    ]
