# Generated by Django 4.1.3 on 2022-11-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintByNumberMeApp', '0005_colorpixel_areasize_colorpixel_xcenter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorpixel',
            name='coorNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='colorpixel',
            name='areaSize',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='colorpixel',
            name='xCenter',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='colorpixel',
            name='yCenter',
            field=models.IntegerField(),
        ),
    ]
