# Generated by Django 4.1.3 on 2022-11-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintByNumberMeApp', '0006_colorpixel_coornum_alter_colorpixel_areasize_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorpixel',
            name='areaSize',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='colorpixel',
            name='xCenter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='colorpixel',
            name='yCenter',
            field=models.IntegerField(default=0),
        ),
    ]
